version: '2'

services:
  neo4j:
    image: dominiquev/neo4j:3.1.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import

  api:
    image: dominiquev/eve-app:0.0
    ports:
      - "5000:5000"
    volumes:
      - ./api:/home/app
    links:
      - neo4j
    depends_on:
      - neo4j